### ISSUE TITLE
Unable to remove all collaborators from a context

### ISSUE THREAD

**Issue by cerpusoddarne** [cerpus/php-edlib#2]
I am unable to remove all tenants from the context.

The endpoint responds with: "CollaboratorContext is not valid"

tenantIds is an empty array in this request

**Comment by maxmoeschinger** [comment]
PR for fix: https://github.com/cerpus/Edlib/pull/93

**Comment by chrieinv** [comment]
Fixed in Edlib v1.5.1: https://github.com/cerpus/Edlib/releases/tag/1.5.1
